import { Card } from './Card.svelte.js'

export const basic_cards = [
    new Card({ series: 'Basic', sequence: 1, title: 'Pupimon', price_multiplier: 3 }),
    new Card({ series: 'Basic', sequence: 2, title: 'Rainog' }),
    new Card({ series: 'Basic', sequence: 3, title: 'Floreon' }),
    new Card({ series: 'Basic', sequence: 4, title: 'Spritzu' }),
    new Card({ series: 'Basic', sequence: 5, title: 'Terrakin', price_multiplier: 1.1 }),
    new Card({ series: 'Basic', sequence: 6, title: 'Zaplume' }),
    new Card({ series: 'Basic', sequence: 7, title: 'Aquaril' }),
    new Card({ series: 'Basic', sequence: 8, title: 'Thornix' }),
    new Card({ series: 'Basic', sequence: 9, title: 'Lithyra' }),
    new Card({ series: 'Basic', sequence: 10, title: 'Glimstun' }),
    new Card({ series: 'Basic', sequence: 11, title: 'Blazrock' }),
    new Card({ series: 'Basic', sequence: 12, title: 'Miradyn' }),
    new Card({ series: 'Basic', sequence: 13, title: 'Sparquill' }),
    new Card({ series: 'Basic', sequence: 14, title: 'Firox' }),
    new Card({ series: 'Basic', sequence: 15, title: 'Volthic' }),
    new Card({ series: 'Basic', sequence: 16, title: 'Nymphlo' }),
    new Card({ series: 'Basic', sequence: 17, title: 'Crystea' }),
    new Card({ series: 'Basic', sequence: 18, title: 'Drazark' }),
    new Card({ series: 'Basic', sequence: 19, title: 'Petalix', price_multiplier: 1.7 }),
    new Card({ series: 'Basic', sequence: 20, title: 'Scorata' }),
    new Card({ series: 'Basic', sequence: 21, title: 'Glimling' }),
    new Card({ series: 'Basic', sequence: 22, title: 'Shylar' }),
    new Card({ series: 'Basic', sequence: 23, title: 'Frostid' }),
    new Card({ series: 'Basic', sequence: 24, title: 'Pyrogon' }),
    new Card({ series: 'Basic', sequence: 25, title: 'Draelith' }),
    new Card({ series: 'Basic', sequence: 26, title: 'Vireon' }),
    new Card({ series: 'Basic', sequence: 27, title: 'Orbuska' }),
    new Card({ series: 'Basic', sequence: 28, title: 'Thornet' }),
    new Card({ series: 'Basic', sequence: 29, title: 'Lumio' }),
    new Card({ series: 'Basic', sequence: 30, title: 'Vulpish' }),
    new Card({ series: 'Basic', sequence: 31, title: 'Glaivor' }),
    new Card({ series: 'Basic', sequence: 32, title: 'Blitzeel' }),
    new Card({ series: 'Basic', sequence: 33, title: 'Mystara' }),
    new Card({ series: 'Basic', sequence: 34, title: 'Pyreth', price_multiplier: 1.3 }),
    new Card({ series: 'Basic', sequence: 35, title: 'Blizara' }),
    new Card({ series: 'Basic', sequence: 36, title: 'Frillush' }),
    new Card({ series: 'Basic', sequence: 37, title: 'Bronzorix', price_multiplier: 1.1 }),
    new Card({ series: 'Basic', sequence: 38, title: 'Silur' }),
    new Card({ series: 'Basic', sequence: 39, title: 'Slynze' }),
    new Card({ series: 'Basic', sequence: 40, title: 'Umbrilith' }),
    new Card({ series: 'Basic', sequence: 41, title: 'Crystorn' }),
    new Card({ series: 'Basic', sequence: 42, title: 'Pezzar' }),
    new Card({ series: 'Basic', sequence: 43, title: 'Drakonis', price_multiplier: 1.5 }),
    new Card({ series: 'Basic', sequence: 44, title: 'Sparix' }),
    new Card({ series: 'Basic', sequence: 45, title: 'Zephylt' }),
    new Card({ series: 'Basic', sequence: 46, title: 'Virex' }),
    new Card({ series: 'Basic', sequence: 47, title: 'Bronteor' }),
    new Card({ series: 'Basic', sequence: 48, title: 'Fluflit' }),
    new Card({ series: 'Basic', sequence: 49, title: 'Rockrune' }),
    new Card({ series: 'Basic', sequence: 50, title: 'Mystleaf', price_multiplier: 1.4 }),
    new Card({ series: 'Basic', sequence: 51, title: 'Gyllet' }),
    new Card({ series: 'Basic', sequence: 51, title: 'Thornake' }),
    new Card({ series: 'Basic', sequence: 52, title: 'Spargon' }),
    new Card({ series: 'Basic', sequence: 53, title: 'Faequill' }),
    new Card({ series: 'Basic', sequence: 54, title: 'Shadorn' }),
    new Card({ series: 'Basic', sequence: 55, title: 'Vexiara' }),
    new Card({ series: 'Basic', sequence: 56, title: 'Cloudor' }),
    new Card({ series: 'Basic', sequence: 57, title: 'Smoldren' }),
    new Card({ series: 'Basic', sequence: 58, title: 'Drigard' }),
    new Card({ series: 'Basic', sequence: 59, title: 'Lilamer' }),
    new Card({ series: 'Basic', sequence: 60, title: 'Stormuck' }),
    new Card({ series: 'Basic', sequence: 61, title: 'Vynkar' }),
    new Card({ series: 'Basic', sequence: 62, title: 'Pyress' }),
    new Card({ series: 'Basic', sequence: 63, title: 'Brambleen' }),
    new Card({ series: 'Basic', sequence: 64, title: 'Embork' }),
    new Card({ series: 'Basic', sequence: 65, title: 'Voltura' }),
    new Card({ series: 'Basic', sequence: 66, title: 'Obelith', price_multiplier: 1.1 }),
    new Card({ series: 'Basic', sequence: 67, title: 'Lithike' }),
    new Card({ series: 'Basic', sequence: 68, title: 'Sparmite' }),
    new Card({ series: 'Basic', sequence: 69, title: 'Sylbreeze' }),
    new Card({ series: 'Basic', sequence: 70, title: 'Fenral' }),
    new Card({ series: 'Basic', sequence: 71, title: 'Spindra' }),
    new Card({ series: 'Basic', sequence: 72, title: 'Virian' }),
    new Card({ series: 'Basic', sequence: 73, title: 'Aethera' }),
    new Card({ series: 'Basic', sequence: 74, title: 'Pyrida' }),
    new Card({ series: 'Basic', sequence: 75, title: 'Yvetark' }),
    new Card({ series: 'Basic', sequence: 76, title: 'Thornis' }),
    new Card({ series: 'Basic', sequence: 77, title: 'Aquadyn' }),
    new Card({ series: 'Basic', sequence: 78, title: 'Igneari' }),
    new Card({ series: 'Basic', sequence: 79, title: 'Lavanet' }),
    new Card({ series: 'Basic', sequence: 80, title: 'Galdron' }),
    new Card({ series: 'Basic', sequence: 81, title: 'Mistrock' }),
    new Card({ series: 'Basic', sequence: 82, title: 'Lumice' }),
    new Card({ series: 'Basic', sequence: 83, title: 'Hydronix', price_multiplier: 1.2 }),
    new Card({ series: 'Basic', sequence: 84, title: 'Flamber' }),
    new Card({ series: 'Basic', sequence: 85, title: 'Dragzire' }),
    new Card({ series: 'Basic', sequence: 86, title: 'Shyllis' }),
    new Card({ series: 'Basic', sequence: 87, title: 'Xylnar' }),
    new Card({ series: 'Basic', sequence: 88, title: 'Magleaf', price_multiplier: 1.5 }),
    new Card({ series: 'Basic', sequence: 89, title: 'Pyrcul' }),
    new Card({ series: 'Basic', sequence: 90, title: 'Ghostael', price_multiplier: 1.2 }),
    new Card({ series: 'Basic', sequence: 91, title: 'Thormine' }),
    new Card({ series: 'Basic', sequence: 92, title: 'Glaciro' }),
    new Card({ series: 'Basic', sequence: 93, title: 'Blitenix' }),
    new Card({ series: 'Basic', sequence: 94, title: 'Vorraxe' }),
    new Card({ series: 'Basic', sequence: 95, title: 'Solunet' }),
    new Card({ series: 'Basic', sequence: 96, title: 'Thundern' }),
    new Card({ series: 'Basic', sequence: 97, title: 'Volpine' }),
    new Card({ series: 'Basic', sequence: 98, title: 'Fawnice' }),
    new Card({ series: 'Basic', sequence: 99, title: 'Cloudera' }),
    new Card({ series: 'Basic', sequence: 100, title: 'Quartzix' }),
    new Card({ series: 'Basic', sequence: 101, title: 'Frostbane', price_multiplier: 2.2 }),
]
